name: cutcitos
description: "Aplicación Cutcitos - Conectando estudiantes vendedores"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'  # Más específico para evitar futuros conflictos

dependencies:
  flutter:
    sdk: flutter

  # Paquetes principales (versiones actualizadas)
  cupertino_icons: ^1.0.8
  intl_phone_field: ^3.2.0
  flutter_dotenv: ^5.1.0  # Versión más reciente
  http: ^1.2.0
  image_picker: ^1.0.4
  flutter_secure_storage: ^9.0.0

  # Agrega estos paquetes útiles para autenticación:
  provider: ^6.1.1       # Para gestión de estado
  shared_preferences: ^2.2.2  # Para almacenamiento local

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  palette_generator: ^0.3.3
  intl: ^0.18.1

flutter:
  uses-material-design: true

  assets:
    - assets/cutcitos.png
    - assets/images/default/
    - assets/images/user/
    - assets/images/products/
    - .env               # Incluye el archivo .env como asset